name: Bump version

on:
  push:
    branches:
      - staging

jobs:
  generate-sys-files:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Get revision
        id: revision
        run: echo ${{ env.REVISION }}
      
      - name: info script run
        run: uname -a > ${{ matrix.os }}_version.txt

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      
      - name: save to artifact
        uses: actions/upload-artifact@v4
        with:
          path: main.pdf
          name: proof.pdf

  bump-version:
    needs: generate-sys-files
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          push: true

      - name: Get revision
        id: revision
        run: echo ${{ env.REVISION }}

      - name: write a file with revision
        run: echo ${{ env.REVISION }} > revision.txt

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          path: artifacts
      
      - name: append version to the end of the filename in artifacts directory
        run: |
          for file in artifacts/*; do
            mv "$file" "${file%.*}_${{ env.REVISION }}.${file##*.}"
          done

      - name: show artifacts directory
        run: ls -la artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
          files: |
            revision.txt
            artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}